services:
  clinic-db:
    container_name: clinic_db_container
    image: postgres:16
    restart: always
    volumes:
      - ./db/sql/01_create_schema.sql:/docker-entrypoint-initdb.d/01_create_schema.sql
      - ./db/sql/02_data.sql:/docker-entrypoint-initdb.d/02_data.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

volumes:
  postgres_data: